
package org.tolven.ws.generator.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4.1-hudson-346-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GeneratorPort", targetNamespace = "http://tolven.org/generator")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GeneratorPort {


    /**
     * 
     * @param startYear
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "urn:generateCCRXML")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateCCRXML", targetNamespace = "http://tolven.org/generator", className = "org.tolven.ws.generator.jaxws.GenerateCCRXMLRequest")
    @ResponseWrapper(localName = "generateCCRXMLResponse", targetNamespace = "http://tolven.org/generator", className = "org.tolven.ws.generator.jaxws.GenerateCCRXMLResponse")
    public byte[] generateCCRXML(
        @WebParam(name = "startYear", targetNamespace = "")
        int startYear);

}
