@echo off
set TOLVEN_USER=admin
echo TOLVEN_USER=%TOLVEN_USER%
set TOLVEN_REALM=tolven
echo TOLVEN_REALM=%TOLVEN_REALM%
set TOLVEN_PASSWORD=sysadmin
echo TOLVEN_PASSWORD=xxxxxxxx
set TOLVEN_CONFIG_DIR=$TOLVEN_CONFIG
echo TOLVEN_CONFIG_DIR=%TOLVEN_CONFIG_DIR%

tpf -version