//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.25 at 11:18:28 AM IST 
//


package org.tolven.mirth;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Message complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Message">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eventPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="documentPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accountId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="processed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Message", propOrder = {
    "eventPath",
    "documentPath",
    "accountId",
    "processed"
})
public class Message {

    @XmlElement(required = true)
    protected String eventPath;
    protected String documentPath;
	protected long accountId;
    protected boolean processed;

    /**
     * Gets the value of the eventPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventPath() {
        return eventPath;
    }

    /**
     * Sets the value of the eventPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventPath(String value) {
        this.eventPath = value;
    }

    /**
     * Gets the value of the accountId property.
     * 
     */
    public long getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     */
    public void setAccountId(long value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the processed property.
     * 
     */
    public boolean isProcessed() {
        return processed;
    }

    /**
     * Sets the value of the processed property.
     * 
     */
    public void setProcessed(boolean value) {
        this.processed = value;
    }
    
    /**
     * Gets the value of the processed property
     * 
     */
    public String getDocumentPath() {
		return documentPath;
	}
    
    /**
     * Sets the value of the documentPath property.
     * 
     */
	public void setDocumentPath(String documentPath) {
		this.documentPath = documentPath;
	}

}
