//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.18 at 05:23:51 PM PDT 
//


package org.tolven.plugin.registry.xml.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:tolven-org:tpf:1.0}doc-ref" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:tolven-org:tpf:1.0}doc-text" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="caption" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "docRef",
    "docText"
})
@XmlRootElement(name = "doc")
public class Doc {

    @XmlElement(name = "doc-ref")
    protected List<DocRef> docRef;
    @XmlElement(name = "doc-text")
    protected DocText docText;
    @XmlAttribute
    protected String caption;

    /**
     * Gets the value of the docRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the docRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocRef }
     * 
     * 
     */
    public List<DocRef> getDocRef() {
        if (docRef == null) {
            docRef = new ArrayList<DocRef>();
        }
        return this.docRef;
    }

    /**
     * Gets the value of the docText property.
     * 
     * @return
     *     possible object is
     *     {@link DocText }
     *     
     */
    public DocText getDocText() {
        return docText;
    }

    /**
     * Sets the value of the docText property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocText }
     *     
     */
    public void setDocText(DocText value) {
        this.docText = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaption(String value) {
        this.caption = value;
    }

}
