
package org.tolven.ws.generator.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4.1-hudson-346-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GeneratorService", targetNamespace = "http://tolven.org/generator", wsdlLocation = "file:/C:/tolvenspace/tolvenWS/wsdl/generator/generator.wsdl")
public class GeneratorService
    extends Service
{

    private final static URL GENERATORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.tolven.ws.generator.jaxws.GeneratorService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.tolven.ws.generator.jaxws.GeneratorService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/tolvenspace/tolvenWS/wsdl/generator/generator.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/tolvenspace/tolvenWS/wsdl/generator/generator.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GENERATORSERVICE_WSDL_LOCATION = url;
    }

    public GeneratorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeneratorService() {
        super(GENERATORSERVICE_WSDL_LOCATION, new QName("http://tolven.org/generator", "GeneratorService"));
    }

    /**
     * 
     * @return
     *     returns GeneratorPort
     */
    @WebEndpoint(name = "GeneratorPort")
    public GeneratorPort getGeneratorPort() {
        return super.getPort(new QName("http://tolven.org/generator", "GeneratorPort"), GeneratorPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeneratorPort
     */
    @WebEndpoint(name = "GeneratorPort")
    public GeneratorPort getGeneratorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tolven.org/generator", "GeneratorPort"), GeneratorPort.class, features);
    }

}
