//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.25 at 09:42:05 PM PDT 
//


package org.tolven.config.model.config.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LDAPServerDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LDAPServerDetail">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tolven-org:tolven-config:1.0}EntityDetail">
 *       &lt;sequence>
 *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contextFactory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="connectionString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="connectionValidString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mdbuser" type="{urn:tolven-org:tolven-config:1.0}MDBUserDetail"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rootPassId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LDAPServerDetail", propOrder = {
    "user",
    "contextFactory",
    "connectionString",
    "connectionValidString",
    "mdbuser"
})
public class LDAPServerDetail
    extends EntityDetail
{

    @XmlElement(required = true)
    protected String user;
    @XmlElement(required = true)
    protected String contextFactory;
    @XmlElement(required = true)
    protected String connectionString;
    @XmlElement(required = true)
    protected String connectionValidString;
    @XmlElement(required = true)
    protected MDBUserDetail mdbuser;
    @XmlAttribute(required = true)
    protected String rootPassId;

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the contextFactory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextFactory() {
        return contextFactory;
    }

    /**
     * Sets the value of the contextFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextFactory(String value) {
        this.contextFactory = value;
    }

    /**
     * Gets the value of the connectionString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionString() {
        return connectionString;
    }

    /**
     * Sets the value of the connectionString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionString(String value) {
        this.connectionString = value;
    }

    /**
     * Gets the value of the connectionValidString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionValidString() {
        return connectionValidString;
    }

    /**
     * Sets the value of the connectionValidString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionValidString(String value) {
        this.connectionValidString = value;
    }

    /**
     * Gets the value of the mdbuser property.
     * 
     * @return
     *     possible object is
     *     {@link MDBUserDetail }
     *     
     */
    public MDBUserDetail getMdbuser() {
        return mdbuser;
    }

    /**
     * Sets the value of the mdbuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDBUserDetail }
     *     
     */
    public void setMdbuser(MDBUserDetail value) {
        this.mdbuser = value;
    }

    /**
     * Gets the value of the rootPassId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootPassId() {
        return rootPassId;
    }

    /**
     * Sets the value of the rootPassId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootPassId(String value) {
        this.rootPassId = value;
    }

}
