//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.25 at 09:42:05 PM PDT 
//


package org.tolven.config.model.config.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.tolven.config.model.config.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.tolven.config.model.config.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AppServerDetail }
     * 
     */
    public AppServerDetail createAppServerDetail() {
        return new AppServerDetail();
    }

    /**
     * Create an instance of {@link DBServerDetail }
     * 
     */
    public DBServerDetail createDBServerDetail() {
        return new DBServerDetail();
    }

    /**
     * Create an instance of {@link WebServerDetail }
     * 
     */
    public WebServerDetail createWebServerDetail() {
        return new WebServerDetail();
    }

    /**
     * Create an instance of {@link LDAPServerDetail }
     * 
     */
    public LDAPServerDetail createLDAPServerDetail() {
        return new LDAPServerDetail();
    }

    /**
     * Create an instance of {@link MDBUserDetail }
     * 
     */
    public MDBUserDetail createMDBUserDetail() {
        return new MDBUserDetail();
    }

    /**
     * Create an instance of {@link EntityDetail }
     * 
     */
    public EntityDetail createEntityDetail() {
        return new EntityDetail();
    }

    /**
     * Create an instance of {@link TolvenConfig }
     * 
     */
    public TolvenConfig createTolvenConfig() {
        return new TolvenConfig();
    }

    /**
     * Create an instance of {@link ApplicationDetail }
     * 
     */
    public ApplicationDetail createApplicationDetail() {
        return new ApplicationDetail();
    }

    /**
     * Create an instance of {@link PasswordServerDetail }
     * 
     */
    public PasswordServerDetail createPasswordServerDetail() {
        return new PasswordServerDetail();
    }

    /**
     * Create an instance of {@link AdminDetail }
     * 
     */
    public AdminDetail createAdminDetail() {
        return new AdminDetail();
    }

    /**
     * Create an instance of {@link RestfulDetail }
     * 
     */
    public RestfulDetail createRestfulDetail() {
        return new RestfulDetail();
    }

}
