/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LDAPMgrPanel.java
 *
 * Created on Jun 21, 2009, 5:33:14 PM
 */

package org.tolven.ldapmgr.gui;

import java.awt.Component;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Joseph Isaac
 */
public class LDAPMgrPanel extends javax.swing.JPanel {

    /** Creates new form LDAPMgrPanel */
    public LDAPMgrPanel() {
        initComponents();
    }
    
    public void addTab(String title, Component component) {
        mainTabbedPane.addTab(title, component);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception ex) {
            throw new RuntimeException("Could not set the Swing Look And Feel", ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mainTabbedPane;
    // End of variables declaration//GEN-END:variables

}
