//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.22 at 03:20:48 PM PDT 
//


package org.tolven.config.model.credential.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.tolven.config.model.credential.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.tolven.config.model.credential.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CertificateGroupDetail }
     * 
     */
    public CertificateGroupDetail createCertificateGroupDetail() {
        return new CertificateGroupDetail();
    }

    /**
     * Create an instance of {@link GroupDetail }
     * 
     */
    public GroupDetail createGroupDetail() {
        return new GroupDetail();
    }

    /**
     * Create an instance of {@link CertificateKeyStoreDetail }
     * 
     */
    public CertificateKeyStoreDetail createCertificateKeyStoreDetail() {
        return new CertificateKeyStoreDetail();
    }

    /**
     * Create an instance of {@link CertificateInfoDetail }
     * 
     */
    public CertificateInfoDetail createCertificateInfoDetail() {
        return new CertificateInfoDetail();
    }

    /**
     * Create an instance of {@link Credentials }
     * 
     */
    public Credentials createCredentials() {
        return new Credentials();
    }

    /**
     * Create an instance of {@link TrustStoreDetail }
     * 
     */
    public TrustStoreDetail createTrustStoreDetail() {
        return new TrustStoreDetail();
    }

    /**
     * Create an instance of {@link TrustStoreCertificateDetail }
     * 
     */
    public TrustStoreCertificateDetail createTrustStoreCertificateDetail() {
        return new TrustStoreCertificateDetail();
    }

    /**
     * Create an instance of {@link KeyStoreCADetail }
     * 
     */
    public KeyStoreCADetail createKeyStoreCADetail() {
        return new KeyStoreCADetail();
    }

    /**
     * Create an instance of {@link CertificateKeyDetail }
     * 
     */
    public CertificateKeyDetail createCertificateKeyDetail() {
        return new CertificateKeyDetail();
    }

    /**
     * Create an instance of {@link Credential }
     * 
     */
    public Credential createCredential() {
        return new Credential();
    }

    /**
     * Create an instance of {@link CertificateDetail }
     * 
     */
    public CertificateDetail createCertificateDetail() {
        return new CertificateDetail();
    }

}
