//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.15 at 10:08:53 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(
		namespace = "urn:tolven-org:trim-data", 
		xmlns = {@javax.xml.bind.annotation.XmlNs(prefix="td", namespaceURI = "urn:tolven-org:trim-data"), 
				 @javax.xml.bind.annotation.XmlNs(prefix="", namespaceURI = "urn:tolven-org:trim:4.0")}, 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.tolven.conceptgroup;
