CREATE SCHEMA app;
COMMENT ON SCHEMA app IS 'Application metadata and extracted instance data';
CREATE SCHEMA core;
COMMENT ON SCHEMA core IS 'User, account, sequence generator and related tables';
CREATE SCHEMA ctom;
COMMENT ON SCHEMA ctom IS 'NCI Clinical Trial Object Model';
CREATE SCHEMA doc;
COMMENT ON SCHEMA doc IS 'Document Metaphor storage';
CREATE SCHEMA flow;
COMMENT ON SCHEMA flow IS 'Business Process Flow';
CREATE SCHEMA gen;
COMMENT ON SCHEMA gen IS 'Seed Data for Virtual Patient Generation';
CREATE SCHEMA jms;
COMMENT ON SCHEMA jms IS 'JMS Message processing';
CREATE SCHEMA provider;
COMMENT ON SCHEMA provider IS 'Provider';
CREATE SCHEMA public;
COMMENT ON SCHEMA public IS 'Default schema';
CREATE SCHEMA umls;
COMMENT ON SCHEMA umls IS 'UMLS Tables';
CREATE SCHEMA who;
COMMENT ON SCHEMA who IS 'World Health Organization Tables';
