
package org.tolven.ws.document.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4.1-hudson-346-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocumentService", targetNamespace = "http://tolven.org/document", wsdlLocation = "file:/C:/tolvenspace/tolvenWS/wsdl/document/document.wsdl")
public class DocumentService
    extends Service
{

    private final static URL DOCUMENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.tolven.ws.document.jaxws.DocumentService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.tolven.ws.document.jaxws.DocumentService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/tolvenspace/tolvenWS/wsdl/document/document.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/tolvenspace/tolvenWS/wsdl/document/document.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCUMENTSERVICE_WSDL_LOCATION = url;
    }

    public DocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentService() {
        super(DOCUMENTSERVICE_WSDL_LOCATION, new QName("http://tolven.org/document", "DocumentService"));
    }

    /**
     * 
     * @return
     *     returns DocumentPort
     */
    @WebEndpoint(name = "DocumentPort")
    public DocumentPort getDocumentPort() {
        return super.getPort(new QName("http://tolven.org/document", "DocumentPort"), DocumentPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentPort
     */
    @WebEndpoint(name = "DocumentPort")
    public DocumentPort getDocumentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tolven.org/document", "DocumentPort"), DocumentPort.class, features);
    }

}
