//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.25 at 09:42:05 PM PDT 
//


package org.tolven.config.model.config.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdminDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdminDetail">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tolven-org:tolven-config:1.0}EntityDetail">
 *       &lt;sequence>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="realm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="secretKeySource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="passwordStoreSource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdminDetail", propOrder = {
    "password",
    "realm",
    "secretKeySource",
    "passwordStoreSource"
})
public class AdminDetail
    extends EntityDetail
{

    @XmlElement(required = true)
    protected String password;
    @XmlElement(required = true)
    protected String realm;
    @XmlElement(required = true)
    protected String secretKeySource;
    @XmlElement(required = true)
    protected String passwordStoreSource;

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the realm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRealm() {
        return realm;
    }

    /**
     * Sets the value of the realm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRealm(String value) {
        this.realm = value;
    }

    /**
     * Gets the value of the secretKeySource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecretKeySource() {
        return secretKeySource;
    }

    /**
     * Sets the value of the secretKeySource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecretKeySource(String value) {
        this.secretKeySource = value;
    }

    /**
     * Gets the value of the passwordStoreSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordStoreSource() {
        return passwordStoreSource;
    }

    /**
     * Sets the value of the passwordStoreSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordStoreSource(String value) {
        this.passwordStoreSource = value;
    }

}
