package oncapps
// See http://wiki.tolven.org/doc/index.php/Plugin:org.tolven.component.tolvenejb#PlaceholderFacts
// for details on the following annotation:
//@use echr placeholders

 /* Tolven */
import java.util.*;
import org.tolven.trim.*;
import org.tolven.trim.ex.*;
import org.tolven.doc.entity.*;
import java.lang.Integer;
import org.tolven.app.entity.MenuStructure;
import org.tolven.app.entity.MenuData;
import org.tolven.app.bean.Mode;
import org.tolven.app.bean.Plan;
import org.tolven.core.entity.Status;
import org.tolven.doc.bean.TolvenMessage;
import org.tolven.model.Patient;
import org.tolven.trim.Observation;
//import org.tolven.process.ScheduleOperations;
import org.tolven.app.PatientListDesignerLocal;
import org.tolven.app.AutomationLocal;
//import org.tolven.app.ShareEncounterSummaryLocal;
//import org.tolven.process.NullifyDuplicateMedications;

global org.tolven.app.AppEvalAdaptor app;
global Date now;
import function org.tolven.trim.contstants.PatientImportance.isVIP;

rule "Initialize PatientListDesignerBean"
	salience 5
	when
		eval(true)
	then
		insert(app.lookupResource( "java:global/tolven/tolvenEJB/PatientListDesignerBean!org.tolven.app.PatientListDesignerLocal" ));
end

rule "Initialize AutomationBean"
salience 35
when
	eval(true)
then
	insert(app.lookupResource( "java:global/tolven/tolvenEJB/AutomationBean!org.tolven.app.AutomationLocal" ));
end


rule "Create Patient List"
	when
			$pldBean:PatientListDesignerLocal()
			Mode( direction == "local" )
			$trim: Trim( name == "patientListDesigner" )
	then
			app.info("**************** Create Patient List *************");
			$pldBean.createPatientList($trim, app);	 
end

rule "Place Patient List Definition on Patient List Definition list"
	when
		$ms: MenuStructure( role == "placeholder", path == "echr:patientListDefinition" )
		$msList: MenuStructure( role == "list", path == "echr:patients:patientListDefinition" )
		$md: MenuData( menuStructure == $ms )
	then
		app.info( "Place Patient List Definition on Patient List Definition list");
		app.createReferenceMD( $md, $msList );
end