
package org.tolven.ws.echo.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4.1-hudson-346-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EchoService", targetNamespace = "http://tolven.org/echo", wsdlLocation = "file:/C:/tolvenspace/tolvenWS/wsdl/echo/echo.wsdl")
public class EchoService
    extends Service
{

    private final static URL ECHOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.tolven.ws.echo.jaxws.EchoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.tolven.ws.echo.jaxws.EchoService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/tolvenspace/tolvenWS/wsdl/echo/echo.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/tolvenspace/tolvenWS/wsdl/echo/echo.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ECHOSERVICE_WSDL_LOCATION = url;
    }

    public EchoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoService() {
        super(ECHOSERVICE_WSDL_LOCATION, new QName("http://tolven.org/echo", "EchoService"));
    }

    /**
     * 
     * @return
     *     returns EchoPort
     */
    @WebEndpoint(name = "EchoPort")
    public EchoPort getEchoPort() {
        return super.getPort(new QName("http://tolven.org/echo", "EchoPort"), EchoPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoPort
     */
    @WebEndpoint(name = "EchoPort")
    public EchoPort getEchoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tolven.org/echo", "EchoPort"), EchoPort.class, features);
    }

}
