
package org.tolven.ws.echo.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4.1-hudson-346-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EchoPort", targetNamespace = "http://tolven.org/echo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EchoPort {


    /**
     * 
     * @param string
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "echo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://tolven.org/echo", className = "org.tolven.ws.echo.jaxws.EchoRequest")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://tolven.org/echo", className = "org.tolven.ws.echo.jaxws.EchoResponse")
    public String echo(
        @WebParam(name = "string", targetNamespace = "")
        String string);

}
