package echr.analysis.chlstrlldl
 /* Tolven */
import java.util.*;

import org.tolven.app.entity.MenuData;
import org.tolven.app.entity.MenuStructure;
import org.tolven.doc.entity.*;
import org.tolven.trim.*;
import org.tolven.trim.ex.*;

import org.tolven.analysis.SnapshotEvent;
import org.tolven.analysis.CHLSTRLLDLSnapshotEvent;
import org.tolven.analysis.SnapshotLocal;
import org.tolven.analysis.AnalysisLocal;
import org.tolven.analysis.AnalysisEvent;
import org.tolven.app.entity.MenuQueryControl;
import org.tolven.app.bean.MenuPath;
import org.tolven.app.MenuLocal;
import org.tolven.app.CCHITLocal;

global org.tolven.app.AppEvalAdaptor app;
global Date now;

rule "Refresh Cohort Lists on change in cohort properties"
	when
		$analysisEvent: AnalysisEvent( command == "update", $cohortType: cohortType)
		$snapshotBean: SnapshotLocal()
		$analysisBean: AnalysisLocal()
		$menuBean: MenuLocal()
		$cchitBean: CCHITLocal()
		$msPatientcohort: MenuStructure( role == "placeholder", path == "echr:patient:patientcohort" )
		$msPatientCohortList: MenuStructure( role == "list", path == "echr:patient:cohorts:current" )
		$msCohortPatientList: MenuStructure( role == "list", path == "echr:cohort:patients" )
		$msCohort: MenuStructure( role == "placeholder", path == "echr:cohort" )
		$msList: MenuStructure( role == "list", path == "echr:analysis:cohorts:all" )
	then
		if($cohortType.equals("org.tolven.cohort.chlstrl")){
			$snapshotBean.deletePatientCohortList(app.getAccount(),"Cholesterol");
			$snapshotBean.deleteCohortPlaceholder(app.getAccount(),"chlstrl");
			$snapshotBean.deleteCohortList(app.getAccount(),"Cholesterol","chlstrl");
			$snapshotBean.deleteAnalysisCohortList(app.getAccount(),"Cholesterol");			
			MenuPath path = new MenuPath("echr:patients:all");
		    MenuQueryControl ctrl=new MenuQueryControl();
			ctrl.setMenuStructurePath("echr:patients:all");
			ctrl.setOriginalTargetPath(path);
			ctrl.setAccountUser(app.getAccountUser());
			MenuData cohort = null;
			List<MenuData> patientList =null;
			MenuData patientcohort=null;
			patientList = $menuBean.findMenuData(ctrl);
			for(MenuData $mdPat: patientList) { 
				patientcohort = $snapshotBean.findPatientcohort("chlstrl", $mdPat, app.getAccount());
				Boolean status = $snapshotBean.validateCohortProperties("chlstrl", $mdPat, app);
				String referenceId = $mdPat.getReferencePath().replace("echr:patient-", "");	
				String contextPath = "echr:patient-"+referenceId+":problems:current";
				Boolean codeStatus = false;
				List<Map<String, Object>> list= $cchitBean.findAllMenuDataList("echr:patient:problems:all",contextPath,"DateSort=DESC",app.getAccountUser());				
				if (list != null && !list.isEmpty()){
					for (Map<String, Object> map : list) {
						codeStatus = $snapshotBean.validateCodeStatusCohortProperties("chlstrl", $mdPat, app, map.get("Code").toString());
						if(codeStatus == true){
							break;
						}
					}
					cohort = $snapshotBean.findCohort("chlstrl",  app.getAccount());
					if(cohort==null) {
						cohort = app.createPlaceholder($msCohort);
					    cohort.setString01("Cholesterol");
					    cohort.setString02("chlstrl");
					    cohort.setDate01(now);
						$snapshotBean.addCohortPlaceholderID("chlstrl", cohort);
						if(status == true && codeStatus == true){
							app.createReferenceMD( cohort, $msList );
						}else {
							$snapshotBean.deleteCohortPlaceholder(app.getAccount(),"chlstrl");
						}
					}
					Map<String, Object> menuDataMap = new HashMap<String, Object>();
					menuDataMap.put("patient", $mdPat.getId());
					menuDataMap.put("cohort", cohort.getId());
					patientcohort = app.createPlaceholder( $msPatientcohort, menuDataMap );
					patientcohort.setDate01( now );
					$snapshotBean.addPatientcohortPlaceholderID("chlstrl", patientcohort);
					if(status == true && codeStatus == true){
						app.createReferenceMD( patientcohort, $msPatientCohortList );
						app.createReferenceMD( patientcohort, $msCohortPatientList, cohort );
					}
				}
			}
		}
	end

rule "Create patientcohort for chlstrl.ldlsnapshot"
	when
		$ms: MenuStructure( role == "placeholder", path == "echr:patient:problem" )
		$md: MenuData( menuStructure == $ms, actStatus!="nullified", $mdPat : parent01 )
		$msPatientcohort: MenuStructure( role == "placeholder", path == "echr:patient:patientcohort" )
		$msCohortPatientList: MenuStructure( role == "list", path == "echr:cohort:patients" )
		$msPatientCohortList: MenuStructure( role == "list", path == "echr:patient:cohorts:current" )
		$msCohort: MenuStructure( role == "placeholder", path == "echr:cohort" )
		$msList: MenuStructure( role == "list", path == "echr:analysis:cohorts:all" )
		$snapshotBean: SnapshotLocal()
	then
		//app.debug( "Create patientcohort for chlstrl.ldlsnapshot" );
		MenuData patientcohort = $snapshotBean.findPatientcohort("chlstrl", $mdPat, app.getAccount());
		Boolean status = $snapshotBean.validateCohortProperties("chlstrl", $mdPat, app);
		Boolean codeStatus = $snapshotBean.validateCodeStatusCohortProperties("chlstrl", $mdPat, app, $md.getString06());
		if(patientcohort == null) {
			MenuData cohort = $snapshotBean.findCohort("chlstrl",  app.getAccount());
			if(cohort == null) {
	            cohort = app.createPlaceholder($msCohort);
	            cohort.setString01("Cholesterol");
	            cohort.setString02("chlstrl");
	            cohort.setDate01(now);
				$snapshotBean.addCohortPlaceholderID("chlstrl", cohort);
				if(status == true && codeStatus == true){
					app.createReferenceMD( cohort, $msList );
				}else {
					$snapshotBean.deleteCohortPlaceholder(app.getAccount(),"chlstrl");
				}
			}
			Map<String, Object> menuDataMap = new HashMap<String, Object>();
			menuDataMap.put("patient", $mdPat.getId());
			menuDataMap.put("cohort", cohort.getId());
			patientcohort = app.createPlaceholder( $msPatientcohort, menuDataMap );
			patientcohort.setDate01( now );
			$snapshotBean.addPatientcohortPlaceholderID("chlstrl", patientcohort);
			if(status == true && codeStatus == true) {
				app.createReferenceMD( patientcohort, $msPatientCohortList );
				app.createReferenceMD( patientcohort, $msCohortPatientList, cohort );
			}
		}
end

rule "Update latest chlstrl.ldlsnapshot"
	when
		$ms: MenuStructure( role == "placeholder", path == "echr:patient:result" )
		$md: MenuData( menuStructure == $ms, $mdPat: parent01, string01 matches "(?i).*ldl.*", pqValue01 != null, $pqValue01: pqValue01, pqUnits01 != null, $pqUnits01: pqUnits01, date01 != null, $date: date01 )
		$snapshotBean: SnapshotLocal()
	then
		//app.debug( "Update latest chlstrl.ldlsnapshot" );
		MenuData patientcohort = $snapshotBean.findPatientcohort( "chlstrl", $mdPat.getId(), app.getAccount() );
		if(patientcohort != null) {
			MenuData lastLDL = (MenuData) patientcohort.getField("lastLDL");
			if(lastLDL == null || (lastLDL.getField("date01") != null && $date.after(lastLDL.getDateField("date01")))) {
				patientcohort.setField("lastLDL", $md);
			}
		}
end

rule "Insert CHLSTRLLDLSnapshotEvent into working memory"
	when
		SnapshotEvent( cohortType == "org.tolven.cohort.chlstrl", snapshotType == "ldlsnapshot", $snapshotType: snapshotType )
		$msSnapshot: MenuStructure( role == "placeholder", path == "echr:cohort:ldlsnapshot" )
		$msSnapshotList: MenuStructure( role == "list", path =="echr:cohort:snapshots:ldlsnapshot" )
		$snapshotBean: SnapshotLocal()
	then
		//app.debug( "Insert CHLSTRLLDLSnapshotEvent into working memory");
		$snapshotBean.deleteAnalysisList(app.getAccount(),"ldlsnapshot");
		MenuData cohort = $snapshotBean.findCohort("chlstrl",  app.getAccount());
		if(cohort != null) {
			List<MenuData> patientcohorts = $snapshotBean.findCohortPatients(cohort, app.getAccount() );
			for( MenuData patientcohort : patientcohorts) {
				insert ( patientcohort );
			}
			Map<String, Object> menuDataMap = new HashMap<String, Object>();
			menuDataMap.put("cohort", cohort.getId());
			MenuData snapshot = app.createPlaceholder( $msSnapshot, menuDataMap );
			snapshot.setString01("Choloesterol LDL");
			snapshot.setDate01( now );
			snapshot.setField("targetPercent", Double.parseDouble(app.getAccount().getProperty().get("org.tolven.cohort.chlstrl.ldlsnapshot.target")));
			snapshot.setField("allCount", 0L);
			snapshot.setField("normCount", 0L);
			snapshot.setField("abnormCount", 0L);
			app.createReferenceMD( snapshot, $msSnapshotList );
			CHLSTRLLDLSnapshotEvent chlstrlldlSnapshotEvent = new CHLSTRLLDLSnapshotEvent();
			chlstrlldlSnapshotEvent.setCohort(cohort);
			chlstrlldlSnapshotEvent.setSnapshot(snapshot);
			chlstrlldlSnapshotEvent.setLdlLow(Double.parseDouble(app.getAccount().getProperty().get("org.tolven.cohort.chlstrl.ldlsnapshot.low")));
			chlstrlldlSnapshotEvent.setLdlHigh(Double.parseDouble(app.getAccount().getProperty().get("org.tolven.cohort.chlstrl.ldlsnapshot.high")));
			insert( chlstrlldlSnapshotEvent );
			$snapshotBean.upateMenuDataVersion( "echr:analysis:portal:chlstrlldlsnapshotsum", app.getAccount(), now );
		}
end

rule "Insert last chlstrl.ldlsnapshot Result into working memory"
	when
		CHLSTRLLDLSnapshotEvent( $cohort: cohort )
		$msPatientcohort: MenuStructure( role == "placeholder", path == "echr:patient:patientcohort" )
		$mdPatientcohort: MenuData( menuStructure == $msPatientcohort, $mdPat: parent01, parent02 == $cohort )
		eval ($mdPatientcohort.getField("lastLDL") != null )
	then
		//app.debug( "Insert last chlstrl.ldlsnapshot Result into working memory" );
		insert($mdPatientcohort.getField("lastLDL"));
end

rule "Create And Insert chlstrl.ldlsnapshot Snapshotresult into working memory"
	when
		CHLSTRLLDLSnapshotEvent( $cohort: cohort, $snapshot: snapshot )
		$msPatientcohort: MenuStructure( role == "placeholder", path == "echr:patient:patientcohort" )
		$mdPatientcohort: MenuData( menuStructure == $msPatientcohort, parent02 == $cohort, $mdPat: parent01 )
		$msResult: MenuStructure( role == "placeholder", path == "echr:patient:result" )
		$mdResult: MenuData( menuStructure == $msResult, parent01 == $mdPat )
		eval ( $mdPatientcohort.getField("lastLDL") != null && $mdPatientcohort.getField("lastLDL").equals($mdResult) )
		$msSnapshotresult: MenuStructure( role == "placeholder", path == "echr:cohort:ldlsnapshot:ldlsnapshotresult" )
	then
		//app.debug( "Create And Insert chlstrl.ldlsnapshot Snapshotresult into working memory" );
		Map<String, Object> menuDataMap = new HashMap<String, Object>();
		menuDataMap.put("ldlsnapshot", $snapshot.getId());
		menuDataMap.put("patient", $mdPat.getId());
		menuDataMap.put("result", $mdResult.getId());
		MenuData mdSnapshotresult = app.createPlaceholder( $msSnapshotresult, menuDataMap );
		mdSnapshotresult.setField("ldlValue", $mdResult.getPqValue01());
		mdSnapshotresult.setField("ldlUnits", $mdResult.getPqUnits01());
		mdSnapshotresult.setField("ldlDate", $mdResult.getDate01());
		insert ( mdSnapshotresult );
end

rule "Create And Insert Null chlstrl.ldlsnapshot Snapshotresult into working memory"
	when
		CHLSTRLLDLSnapshotEvent( $cohort: cohort, $snapshot: snapshot )
		$msPatientcohort: MenuStructure( role == "placeholder", path == "echr:patient:patientcohort" )
		$mdPatientcohort: MenuData( menuStructure == $msPatientcohort, parent02 == $cohort, $mdPat: parent01 )
		eval ( $mdPatientcohort.getField("lastLDL") == null )
		$msSnapshotresult: MenuStructure( role == "placeholder", path == "echr:cohort:ldlsnapshot:ldlsnapshotresult" )
		$snapshotBean: SnapshotLocal()
		$cchitBean: CCHITLocal()
	then
		Boolean status = $snapshotBean.validateCohortProperties("chlstrl", $mdPat, app);
		String referenceId = $mdPat.getPath().replace("echr:patient-", "");	
		String contextPath = "echr:patient-"+referenceId+":problems:current";
		Boolean codeStatus = false;
		List<Map<String, Object>> list= $cchitBean.findAllMenuDataList("echr:patient:problems:all",contextPath,"DateSort=DESC",app.getAccountUser());
		if (list != null && !list.isEmpty()){
			for (Map<String, Object> map : list) {
				codeStatus = $snapshotBean.validateCodeStatusCohortProperties("chlstrl", $mdPat, app, map.get("Code").toString());
					if(codeStatus == true){
						break;
					}
				}
		}
		if(status == true && codeStatus == true) {
		//app.debug( "Create And Insert Null chlstrl.ldlsnapshot Snapshotresult into working memory" );
			Map<String, Object> menuDataMap = new HashMap<String, Object>();
			menuDataMap.put("ldlsnapshot", $snapshot);
			menuDataMap.put("patient", $mdPat);
			MenuData mdSnapshotresult = app.createPlaceholder( $msSnapshotresult, menuDataMap );
			insert ( mdSnapshotresult );
		}
end

rule "Add patientcohorts To chlstrl.ldlsnapshot Snapshot Norm List"
	when
		CHLSTRLLDLSnapshotEvent( $cohort: cohort, $snapshot: snapshot, $ldlLow: ldlLow, $ldlHigh: ldlHigh )
		$msSnapshotresult: MenuStructure( role == "placeholder", path == "echr:cohort:ldlsnapshot:ldlsnapshotresult" )
		$mdSnapshotresult: MenuData( menuStructure == $msSnapshotresult, $mdPat: parent02 )
		eval ( $mdSnapshotresult.getField("ldlValue") != null && $mdSnapshotresult.getDoubleField("ldlValue") <= $ldlHigh )
		$msNormList: MenuStructure( role == "list", path == "echr:cohort:ldlsnapshot:normldl" )
		$msAllList: MenuStructure( role == "list", path == "echr:cohort:ldlsnapshot:all" )
		$msMainNormList: MenuStructure( role == "list", path == "echr:analysis:chlstrlldlsnapshot:normldl" )
		$msMainAllList: MenuStructure( role == "list", path == "echr:analysis:chlstrlldlsnapshot:all" )
	then
		//app.debug( "Add patientcohorts To chlstrl.ldlsnapshot Snapshot Norm List: " + $msNormList);
		app.createReferenceMD( $mdSnapshotresult, $msNormList );
		app.createReferenceMD( $mdSnapshotresult, $msMainNormList );
		long count = $snapshot.getLongField("normCount").longValue();
		$snapshot.setField("normCount", ++count);
		app.createReferenceMD( $mdSnapshotresult, $msAllList );
		app.createReferenceMD( $mdSnapshotresult, $msMainAllList );
		count = $snapshot.getLongField("allCount").longValue();
		$snapshot.setField("allCount", ++count);
end

rule "Add patientcohorts chlstrl.ldlsnapshot Snapshot High List"
	when
		CHLSTRLLDLSnapshotEvent( $cohort: cohort, $snapshot: snapshot, $ldlLow: ldlLow, $ldlHigh: ldlHigh )
		$msSnapshotresult: MenuStructure( role == "placeholder", path == "echr:cohort:ldlsnapshot:ldlsnapshotresult" )
		$mdSnapshotresult: MenuData( menuStructure == $msSnapshotresult, $mdPat: parent02 )
		eval ( $mdSnapshotresult.getField("ldlValue") == null || $mdSnapshotresult.getDoubleField("ldlValue") > $ldlHigh )
		$msHighList: MenuStructure( role == "list", path == "echr:cohort:ldlsnapshot:abnormldl" )
		$msAllList: MenuStructure( role == "list", path == "echr:cohort:ldlsnapshot:all" )
		$msMainHighList: MenuStructure( role == "list", path == "echr:analysis:chlstrlldlsnapshot:abnormldl" )
		$msMainAllList: MenuStructure( role == "list", path == "echr:analysis:chlstrlldlsnapshot:all" )
	then
		//app.debug( "Add patientcohorts chlstrl.ldlsnapshot Snapshot High List: " + $msHighList );
		app.createReferenceMD( $mdSnapshotresult, $msHighList );
		app.createReferenceMD( $mdSnapshotresult, $msMainHighList );
		long count = $snapshot.getLongField("abnormCount").longValue();
		$snapshot.setField("abnormCount", ++count);
		app.createReferenceMD( $mdSnapshotresult, $msAllList );
		app.createReferenceMD( $mdSnapshotresult, $msMainAllList );
		count = $snapshot.getLongField("allCount").longValue();
		$snapshot.setField("allCount", ++count);
end
