//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.03 at 03:14:40 AM PDT 
//


package org.tolven.plugin.repository.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.tolven.plugin.repository.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.tolven.plugin.repository.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConstraintDetail }
     * 
     */
    public ConstraintDetail createConstraintDetail() {
        return new ConstraintDetail();
    }

    /**
     * Create an instance of {@link PluginPropertyDetail }
     * 
     */
    public PluginPropertyDetail createPluginPropertyDetail() {
        return new PluginPropertyDetail();
    }

    /**
     * Create an instance of {@link PluginDetail }
     * 
     */
    public PluginDetail createPluginDetail() {
        return new PluginDetail();
    }

    /**
     * Create an instance of {@link InfoDetail }
     * 
     */
    public InfoDetail createInfoDetail() {
        return new InfoDetail();
    }

    /**
     * Create an instance of {@link MessageDigestDetail }
     * 
     */
    public MessageDigestDetail createMessageDigestDetail() {
        return new MessageDigestDetail();
    }

    /**
     * Create an instance of {@link DependentPluginDetail }
     * 
     */
    public DependentPluginDetail createDependentPluginDetail() {
        return new DependentPluginDetail();
    }

    /**
     * Create an instance of {@link RootPluginDetail }
     * 
     */
    public RootPluginDetail createRootPluginDetail() {
        return new RootPluginDetail();
    }

    /**
     * Create an instance of {@link Plugins }
     * 
     */
    public Plugins createPlugins() {
        return new Plugins();
    }

    /**
     * Create an instance of {@link PluginVersionDetail }
     * 
     */
    public PluginVersionDetail createPluginVersionDetail() {
        return new PluginVersionDetail();
    }

}
